name: Update Naukri Profile
on: push

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install selenium
          pip install webdriver-manager

      - name: Run automation script
        env: 
          NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
        run: |
          python ./naukari-update.py
          ls

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v3
        with:
          name: naukri-screenshot
          path: ./naukri_login_screenshot.png
